---
title: "ProbDist_HK5"
author: "Ashma"
date: "February 19, 2020"
output: html_document
editor_options: 
  chunk_output_type: inline
---

# Simulating and Fitting Data Distribution

```{r}
library(ggplot2) # for graphics
library(MASS) # for maximum likelihood estimation
```


```{r}
# quick and dirty, a truncated normal distribution to work on the solution set

#z <- rnorm(n=3000,mean=0.2) # creates a random uniform distribution of 3000 variables with a mean of 0.2
#z <- data.frame(1:3000,z) # a data frame is created with 1st column 1 to 3000, and second column containing each values made in previous step
#names(z) <- list("ID","myVar") # name given to each column
#z <- z[z$myVar>0,] # take only whose values are greater than 0, basically variables containing 0 and negative numbers are left out
#str(z)
#summary(z$myVar) # gives mean, median and quartiles of the distribution
```

```{r}
z <- read.table("Sample_data.csv",header=TRUE,sep=",", stringsAsFactors=FALSE) # reading my data
str(z)
summary(z)
```

# Data PLotting

* Histogram

```{r}
p1 <- ggplot(data=z, aes(x=zonedia, y=..density..)) +
  geom_histogram(color="grey60",fill="cornsilk",size=0.2) 
print(p1)
```

* Density Curve

```{r}
p1 <-  p1 +  geom_density(linetype="dotted",size=0.75)
print(p1)
```

* Maximum Likelihood parameters

```{r}
normPars <- fitdistr(z$zonedia,"normal")
print(normPars)
str(normPars)
normPars$estimate["mean"] # note structure of getting a named attribute
```

* Plot normal probability density

```{r}
meanML <- normPars$estimate["mean"]
sdML <- normPars$estimate["sd"]

xval <- seq(0,max(z$zonedia),len=length(z$zonedia))

 stat <- stat_function(aes(x = xval, y = ..y..), fun = dnorm, colour="red", n = length(z$zonedia), args = list(mean = meanML, sd = sdML))
 p1 + stat
```

* Plot exponential probability density

```{r}
expoPars <- fitdistr(z$zonedia,"exponential")
rateML <- expoPars$estimate["rate"]

stat2 <- stat_function(aes(x = xval, y = ..y..), fun = dexp, colour="blue", n = length(z$zonedia), args = list(rate=rateML))
 p1 + stat + stat2
```

* Plot uniform probability density

```{r}
stat3 <- stat_function(aes(x = xval, y = ..y..), fun = dunif, colour="darkgreen", n = length(z$zonedia), args = list(min=min(z$zonedia), max=max(z$zonedia)))
 p1 + stat + stat2 + stat3
```

* Plot gamma probability density

```{r}
gammaPars <- fitdistr(z$zonedia,"gamma")
shapeML <- gammaPars$estimate["shape"]
rateML <- gammaPars$estimate["rate"]

stat4 <- stat_function(aes(x = xval, y = ..y..), fun = dgamma, colour="brown", n = length(z$zonedia), args = list(shape=shapeML, rate=rateML))
 p1 + stat + stat2 + stat3 + stat4
```

* Plot beta probability density

```{r}
pSpecial <- ggplot(data=z, aes(x=zonedia/(max(zonedia + 0.1)), y=..density..)) +
  geom_histogram(color="grey60",fill="cornsilk",size=0.2) + 
  xlim(c(0,1)) +
  geom_density(size=0.75,linetype="dotted")

betaPars <- fitdistr(x=z$zonedia/max(z$zonedia + 0.1),start=list(shape1=1,shape2=2),"beta")
shape1ML <- betaPars$estimate["shape1"]
shape2ML <- betaPars$estimate["shape2"]

statSpecial <- stat_function(aes(x = xval, y = ..y..), fun = dbeta, colour="orchid", n = length(z$zonedia), args = list(shape1=shape1ML,shape2=shape2ML))
pSpecial + statSpecial
```


```{r}
# simulating new data set with length, mean and sd as my original data 

z1 <- rnorm(n = length(z$zonedia), mean = meanML, sd = sdML)
z1 <- data.frame(1:length(z$zonedia),z1)
names(z1) <- list("ID","myVar")
z1 <- z1[z1$myVar>0,]
str(z1)
summary(z1$myVar)
```

* histogram

```{r}
p2 <- ggplot(data=z1, aes(x=myVar, y=..density..)) +
  geom_histogram(color="grey60",fill="cornsilk",size=0.2) 
print(p2)
```
 

* Normal Probability density

```{r}
normPars <- fitdistr(z1$myVar,"normal")
print(normPars)
str(normPars)
normPars$estimate["mean"] # note structure of getting a named attribute
```

```{r}
meanML <- normPars$estimate["mean"]
sdML <- normPars$estimate["sd"]

xval <- seq(0,max(z1$myVar),len=length(z1$myVar))

 stat <- stat_function(aes(x = xval, y = ..y..), fun = dnorm, colour="red", n = length(z1$myVar), args = list(mean = meanML, sd = sdML))
 p2 + stat
```

* Density curve

```{r}
p2 <-  p2 +  geom_density(linetype="dotted",size=0.75)
print(p2)
```


```{r}
library(patchwork)
```

```{r}
p1 + p2 # looking both histograms side by side
```


``` 
The histograms for my original dataset and the simulated new dataset do not match with each other. The model is not predicting the realistic data. This might be because I created a random normal data using the parameters like mean and sd from my original data to which the best fitting normal distribution data was created.
```